//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidMarket.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidMarket.DataAccess.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 5 
        ///	a.Id_Activo,
        ///    a.Nombre AS Activo,
        ///    SUM(dc.Cantidad) AS Total_Cantidad,
        ///    SUM(dc.Cantidad * dc.Precio) AS Monto_Total
        ///FROM 
        ///    TransaccionCompra tc
        ///JOIN 
        ///    DetalleCompra dc ON tc.Id_Compra = dc.Id_Compra
        ///JOIN 
        ///    Activo a ON dc.Id_Activo = a.Id_Activo
        ///WHERE 
        ///    tc.Fecha &gt;= DATEADD(DAY, -30, GETDATE())
        ///GROUP BY 
        ///    a.Id_Activo, a.Nombre
        ///ORDER BY 
        ///    Total_Cantidad DESC;.
        /// </summary>
        internal static string ACTIVOS_MAS_COMPRADOS_CANTIDAD {
            get {
                return ResourceManager.GetString("ACTIVOS_MAS_COMPRADOS_CANTIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	SELECT TOP 5
        ///	a.Id_Activo,
        ///    a.Nombre AS Activo,
        ///    SUM(dc.Cantidad) AS Total_Cantidad,
        ///    SUM(dc.Cantidad * dc.Precio) AS Monto_Total
        ///FROM 
        ///    TransaccionCompra tc
        ///JOIN 
        ///    DetalleCompra dc ON tc.Id_Compra = dc.Id_Compra
        ///JOIN 
        ///    Activo a ON dc.Id_Activo = a.Id_Activo
        ///WHERE 
        ///    tc.Fecha &gt;= DATEADD(DAY, -30, GETDATE())
        ///GROUP BY 
        ///    a.Id_Activo, a.Nombre
        ///ORDER BY 
        ///    Monto_Total DESC;.
        /// </summary>
        internal static string ACTIVOS_MAS_COMPRADOS_TOTAL {
            get {
                return ResourceManager.GetString("ACTIVOS_MAS_COMPRADOS_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 5 
        ///	a.Id_Activo,
        ///    a.Nombre AS Activo,
        ///    SUM(dc.Cantidad) AS Total_Cantidad,
        ///    SUM(dc.Cantidad * dc.Precio) AS Monto_Total
        ///FROM 
        ///    TransaccionVenta tv
        ///JOIN 
        ///    DetalleVenta dc ON tv.Id_Venta = dc.Id_Venta
        ///JOIN 
        ///    Activo a ON dc.Id_Activo = a.Id_Activo
        ///WHERE 
        ///    tv.Fecha &gt;= DATEADD(DAY, -30, GETDATE())
        ///GROUP BY 
        ///    a.Id_Activo, a.Nombre
        ///ORDER BY 
        ///    Total_Cantidad DESC;.
        /// </summary>
        internal static string ACTIVOS_MAS_VENDIDOS_CANTIDAD {
            get {
                return ResourceManager.GetString("ACTIVOS_MAS_VENDIDOS_CANTIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	SELECT TOP 5
        ///	a.Id_Activo,
        ///    a.Nombre AS Activo,
        ///    SUM(dc.Cantidad) AS Total_Cantidad,
        ///    SUM(dc.Cantidad * dc.Precio) AS Monto_Total
        ///FROM 
        ///    TransaccionVenta tv
        ///JOIN 
        ///    DetalleVenta dc ON tv.Id_Venta = dc.Id_Venta
        ///JOIN 
        ///    Activo a ON dc.Id_Activo = a.Id_Activo
        ///WHERE 
        ///    tv.Fecha &gt;= DATEADD(DAY, -30, GETDATE())
        ///GROUP BY 
        ///    a.Id_Activo, a.Nombre
        ///ORDER BY 
        ///    Monto_Total DESC;.
        /// </summary>
        internal static string ACTIVOS_MAS_VENDIDOS_TOTAL {
            get {
                return ResourceManager.GetString("ACTIVOS_MAS_VENDIDOS_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT 1 FROM Cliente_Activo WHERE Id_Cliente = @Id_Cliente AND Id_Activo = @Id_Activo)
        ///BEGIN
        ///    DECLARE @NuevaCantidad INT;
        ///    SET @NuevaCantidad = (SELECT Cantidad FROM Cliente_Activo WHERE Id_Cliente = @Id_Cliente AND Id_Activo = @Id_Activo) - @Cantidad;
        ///    
        ///    IF @NuevaCantidad &gt; 0
        ///    BEGIN
        ///        UPDATE Cliente_Activo
        ///        SET Cantidad = @NuevaCantidad
        ///        OUTPUT inserted.Id_Cliente_Activo
        ///        WHERE Id_Cliente = @Id_Cliente AND Id_Activo = @Id_Activo;
        ///    END
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACTUALIZAR_ACTIVO_CLIENTE {
            get {
                return ResourceManager.GetString("ACTUALIZAR_ACTIVO_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cuenta
        ///SET Saldo = @Saldo
        ///WHERE Id_Cuenta = @Id_Cuenta.
        /// </summary>
        internal static string ACTUALIZAR_SALDO {
            get {
                return ResourceManager.GetString("ACTUALIZAR_SALDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Accion (Simbolo, Precio, Id_Activo)
        ///OUTPUT inserted.Id_Accion VALUES (@Simbolo, @Precio, @Id_Activo).
        /// </summary>
        internal static string ADD_ACCION {
            get {
                return ResourceManager.GetString("ADD_ACCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Activo (Nombre)
        ///OUTPUT inserted.Id_Activo VALUES (@Nombre).
        /// </summary>
        internal static string ADD_ACTIVO {
            get {
                return ResourceManager.GetString("ADD_ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Bono (ValorNominal, TasaInteres, Id_Activo)
        ///OUTPUT inserted.Id_Bono VALUES (@ValorNominal, @TasaInteres, @Id_Activo).
        /// </summary>
        internal static string ADD_BONO {
            get {
                return ResourceManager.GetString("ADD_BONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Bitacora (Id_Cliente, Descripcion, Criticidad, Fecha) 
        ///OUTPUT inserted.Id_Bitacora VALUES (@ClienteId, @Descripcion, @Criticidad, @Fecha).
        /// </summary>
        internal static string ALTA_BITACORA {
            get {
                return ResourceManager.GetString("ALTA_BITACORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente
        ///SET Bloqueo = Bloqueo + 1
        ///WHERE ID_Cliente = {0}.
        /// </summary>
        internal static string AUMENTAR_BLOQUEO {
            get {
                return ResourceManager.GetString("AUMENTAR_BLOQUEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM FamiliaPatente WHERE Id_Padre = @PadreId.
        /// </summary>
        internal static string BORRAR_FAMILIA {
            get {
                return ResourceManager.GetString("BORRAR_FAMILIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM UsuarioPermiso WHERE Id_Cliente = @ClienteId.
        /// </summary>
        internal static string BORRAR_PERMISO_USUARIO {
            get {
                return ResourceManager.GetString("BORRAR_PERMISO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente
        ///SET Password = @Password
        ///WHERE Id_Cliente = @Id_Cliente.
        /// </summary>
        internal static string CAMBIAR_PASSWORD {
            get {
                return ResourceManager.GetString("CAMBIAR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cuenta
        ///SET Saldo = Saldo + @Saldo
        ///WHERE Id_Cliente = @Id_Cliente AND Id_Cuenta = @Id_Cuenta.
        /// </summary>
        internal static string CARGAR_SALDO {
            get {
                return ResourceManager.GetString("CARGAR_SALDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DELETE FROM Carrito
        ///	WHERE Id_Carrito = @Id_Carrito AND Id_Cliente = @Id_Cliente.
        /// </summary>
        internal static string ELIMINAR_CARRITO {
            get {
                return ResourceManager.GetString("ELIMINAR_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT activo.Id_Activo, activo.Nombre, accion.Id_Accion, accion.Simbolo, accion.Precio
        ///FROM Accion accion
        ///INNER JOIN Activo activo
        ///ON activo.id_Activo = accion.Id_Activo.
        /// </summary>
        internal static string GET_ACCIONES {
            get {
                return ResourceManager.GetString("GET_ACCIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Bitacora, Id_Cliente, Descripcion, Criticidad, Fecha FROM Bitacora ORDER BY Fecha DESC.
        /// </summary>
        internal static string GET_BITACORA {
            get {
                return ResourceManager.GetString("GET_BITACORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT activo.Id_Activo, activo.Nombre, bono.Id_Bono, bono.ValorNominal, bono.TasaInteres
        ///FROM Bono bono
        ///INNER JOIN Activo activo
        ///ON activo.id_Activo = bono.Id_Activo.
        /// </summary>
        internal static string GET_BONOS {
            get {
                return ResourceManager.GetString("GET_BONOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    c.Id_Carrito,
        ///    c.Id_Activo,
        ///    c.Cantidad,
        ///    ac.Nombre,
        ///    a.Id_Accion,
        ///    a.Simbolo,
        ///    a.Precio,
        ///    b.Id_Bono,
        ///    b.ValorNominal,
        ///    b.TasaInteres,
        ///    CASE 
        ///        WHEN a.Id_Accion IS NOT NULL THEN &apos;Accion&apos;
        ///        ELSE &apos;Bono&apos;
        ///    END AS TipoActivo,
        ///    CASE 
        ///        WHEN a.Id_Accion IS NOT NULL THEN a.Precio * c.Cantidad
        ///        ELSE b.ValorNominal * c.Cantidad
        ///    END AS Total
        ///FROM Carrito c
        ///INNER JOIN Activo ac ON c.Id_Activo = ac.Id_Activo
        ///LEFT JOIN Accio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_CARRITO {
            get {
                return ResourceManager.GetString("GET_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Compra, Id_Cuenta, Id_Cliente, Fecha, Total
        ///FROM TransaccionCompra
        ///WHERE Id_Cliente = {0}.
        /// </summary>
        internal static string GET_COMPRAS {
            get {
                return ResourceManager.GetString("GET_COMPRAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT 
        ///    AC.Id_Cliente_Activo AS Id_Compra,
        ///    NULL AS Id_Cuenta,
        ///    AC.Id_Cliente, 
        ///    (SELECT MAX(TC.Fecha) 
        ///     FROM TransaccionCompra TC 
        ///     WHERE TC.Id_Cliente = AC.Id_Cliente) AS Fecha,
        ///    SUM(COALESCE(a.Precio * AC.Cantidad, b.ValorNominal * AC.Cantidad, 0)) AS Total
        ///FROM Cliente_Activo AC
        ///LEFT JOIN Accion a ON AC.Id_Activo = a.Id_Activo
        ///LEFT JOIN Bono b ON AC.Id_Activo = b.Id_Activo
        ///WHERE AC.Id_Cliente = {0}
        ///  AND AC.Cantidad &gt; 0
        ///GROUP BY AC.Id_Cliente_Activo, AC.Id_C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_COMPRAS_ACTIVAS {
            get {
                return ResourceManager.GetString("GET_COMPRAS_ACTIVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    DC.Id_Detalle,
        ///    DC.Id_Activo,
        ///	B.Id_Bono,
        ///	A.Id_Accion,
        ///    AC.Nombre,
        ///    DC.Id_Compra,
        ///    DC.Cantidad,
        ///    CASE 
        ///        WHEN A.Id_Activo IS NOT NULL THEN &apos;Accion&apos;
        ///        WHEN B.Id_Activo IS NOT NULL THEN &apos;Bono&apos;
        ///        ELSE &apos;Desconocido&apos;
        ///    END AS TipoActivo,
        ///    A.Simbolo,
        ///    B.TasaInteres,
        ///    DC.Precio AS PrecioValorNominal,
        ///    DC.Precio * DC.Cantidad AS Total
        ///FROM 
        ///    DetalleCompra DC
        ///LEFT JOIN Activo AC ON DC.Id_Activo = AC.Id_Activo
        ///LEFT JOIN Accion A ON DC. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_COMPRAS_DETALLE {
            get {
                return ResourceManager.GetString("GET_COMPRAS_DETALLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    AC.Id_Cliente_Activo AS Id_Detalle,
        ///    AC.Id_Activo,
        ///    B.Id_Bono,
        ///    A.Id_Accion,
        ///    Act.Nombre,
        ///    NULL AS Id_Compra,
        ///    AC.Cantidad,
        ///    CASE 
        ///        WHEN A.Id_Activo IS NOT NULL THEN &apos;Accion&apos;
        ///        WHEN B.Id_Activo IS NOT NULL THEN &apos;Bono&apos;
        ///        ELSE &apos;Desconocido&apos;
        ///    END AS TipoActivo,
        ///    A.Simbolo,
        ///    B.TasaInteres,
        ///    COALESCE(A.Precio, B.ValorNominal, 0) AS PrecioValorNominal,
        ///    COALESCE(A.Precio, B.ValorNominal, 0) * AC.Cantidad AS Total
        ///FROM 
        ///    Client [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_COMPRAS_DETALLE_ACTIVAS {
            get {
                return ResourceManager.GetString("GET_COMPRAS_DETALLE_ACTIVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Valor FROM DigitoVerificador WHERE Tabla = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_DIGITO_VERTICAL {
            get {
                return ResourceManager.GetString("GET_DIGITO_VERTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {0}.
        /// </summary>
        internal static string GET_DIGITOS_HORIZONTALES {
            get {
                return ResourceManager.GetString("GET_DIGITOS_HORIZONTALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH RECURSIVO AS (
        ///    SELECT fp.Id_Padre, fp.Id_Hijo 
        ///    FROM FamiliaPatente fp 
        ///    WHERE fp.Id_Padre = {0}
        ///    
        ///    UNION ALL
        ///    
        ///    SELECT fp2.Id_Padre, fp2.Id_Hijo 
        ///    FROM FamiliaPatente fp2 
        ///    INNER JOIN RECURSIVO r ON r.Id_Hijo = fp2.Id_Padre
        ///)
        ///SELECT r.Id_Padre, r.Id_Hijo, p.Id_Permiso, p.Nombre, p.Permiso 
        ///FROM RECURSIVO r 
        ///INNER JOIN Permiso p ON r.Id_Hijo = p.Id_Permiso
        ///GROUP BY r.Id_Padre, r.Id_Hijo, p.Id_Permiso, p.Nombre, p.Permiso;.
        /// </summary>
        internal static string GET_FAMILIA_PATENTE {
            get {
                return ResourceManager.GetString("GET_FAMILIA_PATENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.Id_Permiso, p.Nombre 
        ///FROM FamiliaPatente fm 
        ///INNER JOIN Permiso p ON p.Id_Permiso = fm.Id_Padre
        ///INNER JOIN Permiso p2 ON p2.Id_Permiso = fm.Id_Hijo 
        ///WHERE fm.Id_Hijo = {0};.
        /// </summary>
        internal static string GET_FAMILIA_VALIDACION {
            get {
                return ResourceManager.GetString("GET_FAMILIA_VALIDACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Permiso, Nombre, Permiso FROM Permiso WHERE Permiso IS NULL.
        /// </summary>
        internal static string GET_FAMILIAS {
            get {
                return ResourceManager.GetString("GET_FAMILIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Permiso, Nombre, Permiso FROM Permiso WHERE Permiso IS NOT NULL.
        /// </summary>
        internal static string GET_PATENTES {
            get {
                return ResourceManager.GetString("GET_PATENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Permiso, Nombre, Permiso, Id_Padre, Id_Hijo FROM Permiso p INNER JOIN FamiliaPatente fm on fm.Id_Hijo = p.Id_Permiso WHERE Id_Padre = {0} 
        ///ORDER BY Permiso DESC.
        /// </summary>
        internal static string GET_PATENTES_DE_FAMILIA {
            get {
                return ResourceManager.GetString("GET_PATENTES_DE_FAMILIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Permiso, Nombre, Permiso FROM Permiso p INNER JOIN UsuarioPermiso up on up.Id_Patente = p.Id_Permiso 
        ///WHERE up.Id_Cliente = {0} ORDER BY Permiso DESC.
        /// </summary>
        internal static string GET_PERMISOS_USUARIO {
            get {
                return ResourceManager.GetString("GET_PERMISOS_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 cliente.Id_Cliente, cliente.Email, cliente.Password, cliente.Nombre, cliente.CUIT, cliente.Puntaje, cliente.DVH, cuenta.Id_Cuenta, cuenta.NumeroCuenta, cuenta.Saldo
        ///FROM Cliente cliente
        ///INNER JOIN Cuenta cuenta on cuenta.Id_Cliente = cliente.Id_Cliente
        ///WHERE cliente.Id_Cliente = {0}.
        /// </summary>
        internal static string GET_USUARIO {
            get {
                return ResourceManager.GetString("GET_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.* FROM UsuarioPermiso up INNER JOIN Permiso p on p.Id_Permiso = up.Id_Patente WHERE Id_Cliente = {0}.
        /// </summary>
        internal static string GET_USUARIO_PERMISO {
            get {
                return ResourceManager.GetString("GET_USUARIO_PERMISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT cliente.Id_Cliente, cliente.Email, cliente.Password, cliente.Nombre, cliente.CUIT, cliente.Puntaje, cliente.DVH, cuenta.Id_Cuenta, cuenta.NumeroCuenta, cuenta.Saldo
        ///FROM Cliente cliente
        ///INNER JOIN Cuenta cuenta on cuenta.Id_Cliente = cliente.Id_Cliente .
        /// </summary>
        internal static string GET_USUARIOS {
            get {
                return ResourceManager.GetString("GET_USUARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Usuario_Permiso, Id_Cliente, Id_Patente, DVH 
        ///FROM UsuarioPermiso.
        /// </summary>
        internal static string GET_USUARIOS_PERMISOS {
            get {
                return ResourceManager.GetString("GET_USUARIOS_PERMISOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Venta, Id_Cuenta, Id_Cliente, Fecha, Total
        ///FROM TransaccionVenta
        ///WHERE Id_Cliente = {0}.
        /// </summary>
        internal static string GET_VENTAS {
            get {
                return ResourceManager.GetString("GET_VENTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    DV.Id_Detalle,
        ///    DV.Id_Activo,
        ///	B.Id_Bono,
        ///	A.Id_Accion,
        ///    AC.Nombre,
        ///    DV.Id_Venta,
        ///    DV.Cantidad,
        ///    CASE 
        ///        WHEN A.Id_Activo IS NOT NULL THEN &apos;Accion&apos;
        ///        WHEN B.Id_Activo IS NOT NULL THEN &apos;Bono&apos;
        ///        ELSE &apos;Desconocido&apos;
        ///    END AS TipoActivo,
        ///    A.Simbolo,
        ///    B.TasaInteres,
        ///    DV.Precio AS PrecioValorNominal,
        ///    DV.Precio * DV.Cantidad AS Total
        ///FROM 
        ///    DetalleVenta DV
        ///LEFT JOIN Activo AC ON DV.Id_Activo = AC.Id_Activo
        ///LEFT JOIN Accion A ON DV.Id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_VENTAS_DETALLE {
            get {
                return ResourceManager.GetString("GET_VENTAS_DETALLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Permiso (Nombre, Permiso) OUTPUT inserted.Id_Permiso VALUES (@Nombre, @Permiso).
        /// </summary>
        internal static string GUARDAR_COMPONENTE {
            get {
                return ResourceManager.GetString("GUARDAR_COMPONENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO FamiliaPatente (Id_Padre, Id_Hijo) VALUES (@PadreId, @HijoId);
        ///UPDATE Permiso SET Nombre = @NombreFamilia WHERE Id_Permiso = @FamiliaId;.
        /// </summary>
        internal static string GUARDAR_FAMILIA {
            get {
                return ResourceManager.GetString("GUARDAR_FAMILIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO UsuarioPermiso (Id_Cliente, Id_Patente, DVH) VALUES (@ClienteId, @PatenteId, @DVH).
        /// </summary>
        internal static string GUARDAR_PERMISO_USUARIO {
            get {
                return ResourceManager.GetString("GUARDAR_PERMISO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT 1 FROM Cliente_Activo WHERE Id_Cliente = @Id_Cliente AND Id_Activo = @Id_Activo)
        ///BEGIN
        ///    UPDATE Cliente_Activo
        ///    SET Cantidad = Cantidad + @Cantidad
        ///    OUTPUT inserted.Id_Cliente_Activo
        ///    WHERE Id_Cliente = @Id_Cliente AND Id_Activo = @Id_Activo;
        ///END
        ///ELSE
        ///BEGIN
        ///    INSERT INTO Cliente_Activo (Id_Cliente, Id_Activo, Cantidad)
        ///    OUTPUT inserted.Id_Cliente_Activo
        ///    VALUES (@Id_Cliente, @Id_Activo, @Cantidad);
        ///END
        ///.
        /// </summary>
        internal static string INSERTAR_ACTIVO_CLIENTE {
            get {
                return ResourceManager.GetString("INSERTAR_ACTIVO_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT 1 FROM Carrito WHERE Id_Activo = @Id_Activo AND Id_Cliente = @Id_Cliente)
        ///BEGIN
        ///    UPDATE Carrito
        ///    SET Cantidad = Cantidad + 1
        ///    WHERE Id_Activo = @Id_Activo AND Id_Cliente = @Id_Cliente;
        ///END
        ///ELSE
        ///BEGIN
        ///    INSERT INTO Carrito (Id_Activo, Id_Cliente, Cantidad)
        ///    VALUES (@Id_Activo, @Id_Cliente, 1);
        ///END.
        /// </summary>
        internal static string INSERTAR_CARRITO {
            get {
                return ResourceManager.GetString("INSERTAR_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO DetalleCompra (Id_Activo, Id_Compra, Cantidad, Precio)
        ///OUTPUT inserted.Id_Detalle
        ///VALUES (@Id_Activo, @Id_Compra, @Cantidad, @Precio).
        /// </summary>
        internal static string INSERTAR_DETALLE_COMPRA {
            get {
                return ResourceManager.GetString("INSERTAR_DETALLE_COMPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO DetalleVenta (Id_Activo, Id_Venta, Cantidad, Precio)
        ///OUTPUT inserted.Id_Detalle
        ///VALUES (@Id_Activo, @Id_Venta, @Cantidad, @Precio).
        /// </summary>
        internal static string INSERTAR_DETALLE_VENTA {
            get {
                return ResourceManager.GetString("INSERTAR_DETALLE_VENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TransaccionCompra (Id_Cuenta, Id_Cliente, Fecha, Total)
        ///OUTPUT inserted.Id_Compra
        ///VALUES (@Id_Cuenta, @Id_Cliente, @Fecha, @Total).
        /// </summary>
        internal static string INSERTAR_TRANSACCION_COMPRA {
            get {
                return ResourceManager.GetString("INSERTAR_TRANSACCION_COMPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TransaccionVenta (Id_Cuenta, Id_Cliente, Fecha, Total)
        ///OUTPUT inserted.Id_Venta
        ///VALUES (@Id_Cuenta, @Id_Cliente, @Fecha, @Total).
        /// </summary>
        internal static string INSERTAR_TRANSACCION_VENTA {
            get {
                return ResourceManager.GetString("INSERTAR_TRANSACCION_VENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	DELETE FROM Carrito
        ///	WHERE Id_Cliente = @Id_Cliente.
        /// </summary>
        internal static string LIMPIAR_CARRITO {
            get {
                return ResourceManager.GetString("LIMPIAR_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 cliente.Id_Cliente, cliente.Email, cliente.Password, cliente.Nombre, cliente.CUIT, cliente.Puntaje, cliente.Bloqueo, cliente.DVH, cuenta.Id_Cuenta, cuenta.NumeroCuenta, cuenta.Saldo
        ///FROM Cliente cliente
        ///INNER JOIN Cuenta cuenta on cuenta.Id_Cliente = cliente.Id_Cliente 
        ///WHERE Email = &apos;{0}&apos;.
        /// </summary>
        internal static string LOGIN_USUARIO {
            get {
                return ResourceManager.GetString("LOGIN_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente
        ///SET Email = @Email, Nombre = @Nombre, CUIT = @CUIT, DVH = @DVH
        ///WHERE Id_Cliente = @Id_Cliente.
        /// </summary>
        internal static string MODIFICAR_USUARIO {
            get {
                return ResourceManager.GetString("MODIFICAR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Cantidad
        ///FROM Cliente_Activo
        ///WHERE Id_Activo = {0} AND Id_Cliente = {1}.
        /// </summary>
        internal static string OBTENER_CANTIDAD_REAL_CLIENTE {
            get {
                return ResourceManager.GetString("OBTENER_CANTIDAD_REAL_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    CASE 
        ///        WHEN a.Id_Activo IN (SELECT Id_Activo FROM accion) THEN ac.Precio
        ///        WHEN a.Id_Activo IN (SELECT Id_Activo FROM bono) THEN b.ValorNominal
        ///    END AS Precio
        ///FROM activo a
        ///LEFT JOIN accion ac ON a.Id_Activo = ac.Id_Activo
        ///LEFT JOIN bono b ON a.Id_Activo = b.Id_Activo
        ///WHERE a.Id_Activo = {0}.
        /// </summary>
        internal static string OBTENER_PRECIO_ACTUAL {
            get {
                return ResourceManager.GetString("OBTENER_PRECIO_ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH ActivosComprados AS (
        ///    SELECT 
        ///        AC.Id_Activo,
        ///        act.Nombre,
        ///        AC.Cantidad,
        ///        CASE 
        ///            WHEN a.Precio IS NOT NULL THEN a.Precio
        ///            WHEN b.ValorNominal IS NOT NULL THEN b.ValorNominal
        ///            ELSE 0
        ///        END AS ValorActual
        ///    FROM Cliente_Activo AC
        ///    LEFT JOIN Accion a ON AC.Id_Activo = a.Id_Activo
        ///    LEFT JOIN Bono b ON AC.Id_Activo = b.Id_Activo
        ///    LEFT JOIN Activo act ON AC.Id_Activo = act.Id_Activo
        ///    WHERE AC.Id_Cliente = {0}
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OBTENER_TOTAL_INVERTIDO {
            get {
                return ResourceManager.GetString("OBTENER_TOTAL_INVERTIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 Total as UltimaTransaccion
        ///FROM TransaccionCompra
        ///WHERE Id_Cliente = {0}
        ///ORDER BY Fecha DESC.
        /// </summary>
        internal static string OBTENER_ULTIMA_TRANSACCION {
            get {
                return ResourceManager.GetString("OBTENER_ULTIMA_TRANSACCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @rutaCompleta NVARCHAR(255) = @RutaBackupParam;
        ///DECLARE @nombreBase NVARCHAR(255) = @NombreBaseParam;
        ///
        ///DECLARE @backupQuery NVARCHAR(MAX) = &apos;BACKUP DATABASE [&apos; + @nombreBase + &apos;] TO DISK = &apos;&apos;&apos; + @rutaCompleta + &apos;&apos;&apos; WITH FORMAT, MEDIANAME = &apos;&apos;SQLServerBackups&apos;&apos;, NAME = &apos;&apos;Full Backup of &apos; + @nombreBase + &apos;&apos;&apos;&apos;;
        ///
        ///EXEC(@backupQuery);.
        /// </summary>
        internal static string REALIZAR_BACKUP {
            get {
                return ResourceManager.GetString("REALIZAR_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente
        ///SET Password = @Password, Bloqueo = 0
        ///WHERE Email = @Email.
        /// </summary>
        internal static string REESTABLECER_PASSWORD {
            get {
                return ResourceManager.GetString("REESTABLECER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Cliente (Email, Password, Nombre, CUIT, Puntaje, Bloqueo, DVH)
        ///OUTPUT inserted.Id_Cliente
        ///VALUES (@Email, @Password, @Nombre, @CUIT, 0.0, @Bloqueo, @DVH);
        ///
        ///DECLARE @IdCliente INT;
        ///SET @IdCliente = SCOPE_IDENTITY();
        ///
        ///INSERT INTO Cuenta (Id_Cliente, NumeroCuenta, Saldo)
        ///VALUES (@IdCliente, NEXT VALUE FOR dbo.NumeroCuentaSeq, 50000.0);.
        /// </summary>
        internal static string REGISTRAR_USUARIO {
            get {
                return ResourceManager.GetString("REGISTRAR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Activo
        ///SET Nombre = @Nombre
        ///WHERE Id_Activo = @Id_Activo
        ///
        ///UPDATE Accion
        ///SET Simbolo = @Simbolo, Precio = @Precio
        ///WHERE Id_Accion = @Id_Accion.
        /// </summary>
        internal static string UPDATE_ACCION {
            get {
                return ResourceManager.GetString("UPDATE_ACCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente
        ///SET Bloqueo = 0
        ///WHERE ID_Cliente = {0}.
        /// </summary>
        internal static string UPDATE_BLOQUEO {
            get {
                return ResourceManager.GetString("UPDATE_BLOQUEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Activo
        ///SET Nombre = @Nombre
        ///WHERE Id_Activo = @Id_Activo
        ///
        ///UPDATE Bono
        ///SET ValorNominal = @ValorNominal, TasaInteres = @TasaInteres
        ///WHERE Id_Bono = @Id_Bono.
        /// </summary>
        internal static string UPDATE_BONO {
            get {
                return ResourceManager.GetString("UPDATE_BONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	UPDATE Carrito
        ///	SET Cantidad = @Cantidad
        ///	WHERE Id_Activo = @Id_Activo and Id_Cliente = @Id_Cliente.
        /// </summary>
        internal static string UPDATE_CARRITO {
            get {
                return ResourceManager.GetString("UPDATE_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DigitoVerificador SET Valor = @Valor OUTPUT inserted.Id_DigitoVerificador WHERE Tabla = @Tabla.
        /// </summary>
        internal static string UPDATE_DIGITO_VERTICAL {
            get {
                return ResourceManager.GetString("UPDATE_DIGITO_VERTICAL", resourceCulture);
            }
        }
    }
}
