//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MidMarket.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MidMarket.DataAccess.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Bitacora (Id_Cliente, Descripcion, Criticidad, Fecha) 
        ///OUTPUT inserted.Id_Bitacora VALUES (@ClienteId, @Descripcion, @Criticidad, @Fecha).
        /// </summary>
        internal static string ALTA_BITACORA {
            get {
                return ResourceManager.GetString("ALTA_BITACORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente
        ///SET Bloqueo = Bloqueo + 1
        ///WHERE ID_Cliente = {0}.
        /// </summary>
        internal static string AUMENTAR_BLOQUEO {
            get {
                return ResourceManager.GetString("AUMENTAR_BLOQUEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM FamiliaPatente WHERE Id_Padre = @PadreId.
        /// </summary>
        internal static string BORRAR_FAMILIA {
            get {
                return ResourceManager.GetString("BORRAR_FAMILIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM UsuarioPermiso WHERE Id_Cliente = @ClienteId.
        /// </summary>
        internal static string BORRAR_PERMISO_USUARIO {
            get {
                return ResourceManager.GetString("BORRAR_PERMISO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 30 Id_Bitacora, Id_Cliente, Descripcion, Criticidad, Fecha FROM Bitacora ORDER BY Fecha DESC.
        /// </summary>
        internal static string GET_BITACORA {
            get {
                return ResourceManager.GetString("GET_BITACORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Valor FROM DigitoVerificador WHERE Tabla = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_DIGITO_VERTICAL {
            get {
                return ResourceManager.GetString("GET_DIGITO_VERTICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM {0}.
        /// </summary>
        internal static string GET_DIGITOS_HORIZONTALES {
            get {
                return ResourceManager.GetString("GET_DIGITOS_HORIZONTALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH RECURSIVO AS (
        ///    SELECT fp.Id_Padre, fp.Id_Hijo 
        ///    FROM FamiliaPatente fp 
        ///    WHERE fp.Id_Padre = {0}
        ///    
        ///    UNION ALL
        ///    
        ///    SELECT fp2.Id_Padre, fp2.Id_Hijo 
        ///    FROM FamiliaPatente fp2 
        ///    INNER JOIN RECURSIVO r ON r.Id_Hijo = fp2.Id_Padre
        ///)
        ///SELECT r.Id_Padre, r.Id_Hijo, p.Id_Permiso, p.Nombre, p.Permiso 
        ///FROM RECURSIVO r 
        ///INNER JOIN Permiso p ON r.Id_Hijo = p.Id_Permiso
        ///GROUP BY r.Id_Padre, r.Id_Hijo, p.Id_Permiso, p.Nombre, p.Permiso;.
        /// </summary>
        internal static string GET_FAMILIA_PATENTE {
            get {
                return ResourceManager.GetString("GET_FAMILIA_PATENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.Id_Permiso, p.Nombre 
        ///FROM FamiliaPatente fm 
        ///INNER JOIN Permiso p ON p.Id_Permiso = fm.Id_Padre
        ///INNER JOIN Permiso p2 ON p2.Id_Permiso = fm.Id_Hijo 
        ///WHERE fm.Id_Hijo = {0};.
        /// </summary>
        internal static string GET_FAMILIA_VALIDACION {
            get {
                return ResourceManager.GetString("GET_FAMILIA_VALIDACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Permiso, Nombre, Permiso FROM Permiso WHERE Permiso IS NULL.
        /// </summary>
        internal static string GET_FAMILIAS {
            get {
                return ResourceManager.GetString("GET_FAMILIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Permiso, Nombre, Permiso FROM Permiso WHERE Permiso IS NOT NULL.
        /// </summary>
        internal static string GET_PATENTES {
            get {
                return ResourceManager.GetString("GET_PATENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Permiso, Nombre, Permiso, Id_Padre, Id_Hijo FROM Permiso p INNER JOIN FamiliaPatente fm on fm.Id_Hijo = p.Id_Permiso WHERE Id_Padre = {0} 
        ///ORDER BY Permiso DESC.
        /// </summary>
        internal static string GET_PATENTES_DE_FAMILIA {
            get {
                return ResourceManager.GetString("GET_PATENTES_DE_FAMILIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Permiso, Nombre, Permiso FROM Permiso p INNER JOIN UsuarioPermiso up on up.Id_Patente = p.Id_Permiso 
        ///WHERE up.Id_Cliente = {0} ORDER BY Permiso DESC.
        /// </summary>
        internal static string GET_PERMISOS_USUARIO {
            get {
                return ResourceManager.GetString("GET_PERMISOS_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 cliente.Id_Cliente, cliente.Email, cliente.Password, cliente.Nombre, cliente.CUIT, cliente.Puntaje, cliente.DVH, cuenta.Id_Cuenta, cuenta.NumeroCuenta, cuenta.Saldo
        ///FROM Cliente cliente
        ///INNER JOIN Cuenta cuenta on cuenta.Id_Cliente = cliente.Id_Cliente
        ///WHERE cliente.Id_Cliente = {0}.
        /// </summary>
        internal static string GET_USUARIO {
            get {
                return ResourceManager.GetString("GET_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.* FROM UsuarioPermiso up INNER JOIN Permiso p on p.Id_Permiso = up.Id_Patente WHERE Id_Cliente = {0}.
        /// </summary>
        internal static string GET_USUARIO_PERMISO {
            get {
                return ResourceManager.GetString("GET_USUARIO_PERMISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT cliente.Id_Cliente, cliente.Email, cliente.Password, cliente.Nombre, cliente.CUIT, cliente.Puntaje, cliente.DVH, cuenta.Id_Cuenta, cuenta.NumeroCuenta, cuenta.Saldo
        ///FROM Cliente cliente
        ///INNER JOIN Cuenta cuenta on cuenta.Id_Cliente = cliente.Id_Cliente .
        /// </summary>
        internal static string GET_USUARIOS {
            get {
                return ResourceManager.GetString("GET_USUARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id_Usuario_Permiso, Id_Cliente, Id_Patente, DVH 
        ///FROM UsuarioPermiso.
        /// </summary>
        internal static string GET_USUARIOS_PERMISOS {
            get {
                return ResourceManager.GetString("GET_USUARIOS_PERMISOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Permiso (Nombre, Permiso) OUTPUT inserted.Id_Permiso VALUES (@Nombre, @Permiso).
        /// </summary>
        internal static string GUARDAR_COMPONENTE {
            get {
                return ResourceManager.GetString("GUARDAR_COMPONENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO FamiliaPatente (Id_Padre, Id_Hijo) VALUES (@PadreId, @HijoId);
        ///UPDATE Permiso SET Nombre = @NombreFamilia WHERE Id_Permiso = @FamiliaId;.
        /// </summary>
        internal static string GUARDAR_FAMILIA {
            get {
                return ResourceManager.GetString("GUARDAR_FAMILIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO UsuarioPermiso (Id_Cliente, Id_Patente, DVH) VALUES (@ClienteId, @PatenteId, @DVH).
        /// </summary>
        internal static string GUARDAR_PERMISO_USUARIO {
            get {
                return ResourceManager.GetString("GUARDAR_PERMISO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 cliente.Id_Cliente, cliente.Email, cliente.Password, cliente.Nombre, cliente.CUIT, cliente.Puntaje, cliente.DVH, cuenta.Id_Cuenta, cuenta.NumeroCuenta, cuenta.Saldo
        ///FROM Cliente cliente
        ///INNER JOIN Cuenta cuenta on cuenta.Id_Cliente = cliente.Id_Cliente 
        ///WHERE Email = &apos;{0}&apos;.
        /// </summary>
        internal static string LOGIN_USUARIO {
            get {
                return ResourceManager.GetString("LOGIN_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @rutaCompleta NVARCHAR(255) = @RutaBackupParam;
        ///DECLARE @nombreBase NVARCHAR(255) = @NombreBaseParam;
        ///
        ///DECLARE @backupQuery NVARCHAR(MAX) = &apos;BACKUP DATABASE [&apos; + @nombreBase + &apos;] TO DISK = &apos;&apos;&apos; + @rutaCompleta + &apos;&apos;&apos; WITH FORMAT, MEDIANAME = &apos;&apos;SQLServerBackups&apos;&apos;, NAME = &apos;&apos;Full Backup of &apos; + @nombreBase + &apos;&apos;&apos;&apos;;
        ///
        ///EXEC(@backupQuery);.
        /// </summary>
        internal static string REALIZAR_BACKUP {
            get {
                return ResourceManager.GetString("REALIZAR_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Cliente (Email, Password, Nombre, CUIT, Puntaje, DVH)
        ///OUTPUT inserted.Id_Cliente
        ///VALUES (@Email, @Password, @Nombre, @CUIT, 0.0, @DVH);
        ///
        ///DECLARE @IdCliente INT;
        ///SET @IdCliente = SCOPE_IDENTITY();
        ///
        ///INSERT INTO Cuenta (Id_Cliente, NumeroCuenta, Saldo)
        ///VALUES (@IdCliente, NEXT VALUE FOR dbo.NumeroCuentaSeq, 50000.0);.
        /// </summary>
        internal static string REGISTRAR_USUARIO {
            get {
                return ResourceManager.GetString("REGISTRAR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Cliente
        ///SET Bloqueo = 0
        ///WHERE ID_Cliente = {0}.
        /// </summary>
        internal static string UPDATE_BLOQUEO {
            get {
                return ResourceManager.GetString("UPDATE_BLOQUEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DigitoVerificador SET Valor = @Valor OUTPUT inserted.Id_DigitoVerificador WHERE Tabla = @Tabla.
        /// </summary>
        internal static string UPDATE_DIGITO_VERTICAL {
            get {
                return ResourceManager.GetString("UPDATE_DIGITO_VERTICAL", resourceCulture);
            }
        }
    }
}
