namespace MidMarket.Entities.Enums
{
    public enum Permiso
    {
        EsFamilia,
        AdministracionFamilias,
        AltaFamilia,
        ModificarFamilia,
        BajaFamilia,
        AsignarFamilias,
        AsignarPatentes,
        DesasignarFamilias,
        DesasignarPatentes,
        AltaBono,
        ModificarBono,
        BajaBono,
        AltaAccion,
        ModificarAccion,
        BajaAccion,
        VisualizarPortafolio,
        ComprarAccion,
        ComprarBono,
        VenderAccion,
        VenderBono,
        VisualizarBitacora,
        AdministracionUsuarios,
        AltaUsuario,
        ModificacionUsuario,
        BajaUsuario,
        AdministracionBaseDeDatos
    }
}
